services:
  - type: web
    name: discord-music-bot
    runtime: python
    region: singapore
    plan: free
    buildCommand: |
      curl -fsSL https://deno.land/install.sh | sh
      pip install -r requirements.txt
    startCommand: python3 bot.py
